# -*- coding: utf-8 -*-
"""Aula5- Multivis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1So-nUCTnAngqT6F7Kaz3t13gNcN1CLuM
"""

import plotly.express as px
import pandas as pd

df = px.data.iris()
df

fig = px.scatter_matrix(df,
                        dimensions = ['sepal_length', 'sepal_width','petal_length','petal_width'],
                        color= 'species')

fig.show()

# legenda é interativa'

fig = px.parallel_coordinates(df, color= 'species_id',
                              dimensions = ['sepal_length', 'sepal_width','petal_length','petal_width'],
                              )

fig.show()

from sklearn.manifold import TSNE

df

features = df.loc[:, ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
features

tsne = TSNE(n_components=2)

projections = tsne.fit_transform(features)

fig= px.scatter(projections, x=0, y=1, color = df.species)


fig.show()

tsne = TSNE(n_components=3)

projections = tsne.fit_transform(features)

fig= px.scatter_3d(projections, x=0, y=1, z=2, color = df.species)


fig.show()